### ISSUE TITLE
Expose the GraphQL-Java-client's `ParserOptions`

### ISSUE THREAD

**Issue by sschuberth** [ermadmi78/kobby#25]
It might be necessary to configure things like [maxTokens](https://github.com/graphql-java/graphql-java/blob/113db6b09097f64383bfc9a9d5c745b011774e81/src/main/java/graphql/parser/ParserOptions.java#L207-L216), so it would be nice if the `ParserOptions` were exposed via the Gradle plugin extension.

**Comment by ermadmi78** [comment]
The Kobby plugin does not parse queries at runtime. It just generates the client DSL at compile time. So these parser options only affect how the schema is parsed at compile time. Is it really necessary? 
The DSL generated by the Kobby plugin only works on the client side at runtime and just generates GraphQL queries.
To protect your server from hacker attacks, you need to configure a server side framework.

**Comment by sschuberth** [comment]
> Is it really necessary?

Unfortunately yes. For some background information see the related issues at https://github.com/ExpediaGroup/graphql-kotlin/issues/1303 and https://github.com/ExpediaGroup/graphql-kotlin/issues/1526.

**Comment by ermadmi78** [comment]
Ok, I understand you. Thank you. I agree it needs to be supported.

**Comment by ermadmi78** [comment]
Hi, @sschuberth 

Could you please provide a scenario to reproduce the problem, which should be solved by configuring the parser options? As far as I understand, the problem may arise when generating the DSL for giant GraphQL schemas. To reproduce the problem, I tried to create a DSL for the official [GitHub GraphQL schema](https://github.com/octokit/graphql-schema/blob/master/schema.graphql). It is a great test case. I found a few bugs (#27, #28) fixed in version `2.0.0-beta.01`. But these bugs have nothing to do with the parser options. Now the DSL for this scheme is generated correctly. You can see an example here:

[kobby-github-graphql-dsl](https://github.com/ermadmi78/kobby-github-graphql-dsl)

**Comment by sschuberth** [comment]
> Could you please provide a scenario to reproduce the problem, which should be solved by configuring the parser options?

Thanks for the update. I'll try to port our code to the latest beta of Kobby to reproduce the problem, and will report back here.

**Comment by sschuberth** [comment]
> I'll try to port our code to the latest beta of Kobby to reproduce the problem, and will report back here.

Unfortunately, I'm now somewhat blocked by https://github.com/ermadmi78/kobby/issues/7 as our code exclusively uses kotlinx-serialization... it will probably take me some time to rewrite that code.

**Comment by ermadmi78** [comment]
Yes, unfortunately, for a year now, hands have not reached this task. I'll try to find time before the end of the year, but so far I can't promise anything. Very busy at work :)

**Comment by ermadmi78** [comment]
> I'm not sure why, but our current use of https://github.com/ExpediaGroup/graphql-kotlin takes way less memory (512 MB is enough).

According to my research, the Kobby plugin uses the same 512 MB to generate code, and then the Kotlin compiler uses about 3 GB to compile the generated code. It's just that ExpediaGroup is not a code generation library, so they don't have a code compilation step.
